- name: delete kube-router network_plugin
  shell: "kubectl delete -f {{ yaml_dir }}/kube-router.yaml"
  delegate_to: "{{ groups['k8s-console'][0] }}"
  ignore_errors: true
  run_once: yes


- name: delete calico network_plugin if exists
  shell: "kubectl delete -f {{ yaml_dir }}/calico.yaml"
  delegate_to: "{{ groups['k8s-console'][0] }}"
  ignore_errors: true
  run_once: yes

- name: uninstall other network plugin relationship files if exists
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/cni
    - /usr/lib/systemd/system/calico-node.service

- name: create network plugin require dir
  file:
    path: "{{ item }}"
    mode: 0755
    state: directory
    recurse: yes
  with_items:
    - "{{ kube_cni_bin_dir }}"

- name: sync flannel network plugin
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "{{ cni_binary_dir }}/bridge", dest: "{{ kube_cni_bin_dir }}/" }
    - { src: "{{ cni_binary_dir }}/flannel", dest: "{{ kube_cni_bin_dir }}/" }
    - { src: "{{ cni_binary_dir }}/host-local", dest: "{{ kube_cni_bin_dir }}/" }
    - { src: "{{ cni_binary_dir }}/loopback", dest: "{{ kube_cni_bin_dir }}/" }

- name: create yaml file require directory
  file:
    path: "{{ yaml_dir }}"
    state: directory
  delegate_to: "{{ groups['k8s-console'][0] }}"


- name: Generate Deployment YAML
  template:
    src: "flannel.yaml.j2"
    dest: "{{ yaml_dir }}/flannel.yaml"
  delegate_to: "{{ groups['k8s-console'][0] }}"

- name: create flannel network_plugin
  shell: "kubectl apply -f {{ yaml_dir }}/flannel.yaml"
  delegate_to: "{{ groups['k8s-console'][0] }}"
  run_once: yes
