# install pod_network_plugin ,default is calico
- name: install network_plugin | install calico
  include_tasks: "calico_install.yaml"
  when: kube_proxy_enabled and network_plugin is calico

- name: install network_plugin | install kube-router
  include_tasks: "kube_router_install.yaml"
  when: not kube_proxy_enabled


- name: install network_plugin | install flannel
  include_tasks: "flannel_install.yaml"
  when: kube_proxy_enabled and network_plugin is flannel
