- hosts: all
  become: yes
  roles:
    - preinstall

- hosts: k8s-console
  become: yes
  roles:
    - download
    - makessl
    - docker
    - master-lb
    - { role: kubernetes/client }

- hosts: k8s-master
  become: yes
  roles:
    - etcd
    - { role: kubernetes/master }
    - docker
    - master-lb
    - { role: kubernetes/node }

- hosts: k8s-node
  become: yes
  roles:
    - docker
    - master-lb
    - { role: kubernetes/node }
    - { role: kubernetes/network-plugin }
