- hosts: all
  remote_user: vagrant
  become: yes
  roles:
    - preinstall

- hosts: k8s-console
  remote_user: vagrant
  become: yes
  roles:
    - download
    - makessl
    - master-lb
    - client

- hosts: k8s-master
  remote_user: vagrant
  become: yes
  roles:
    - master
    - etcd

- hosts: k8s-node
  remote_user: vagrant
  become: yes
  roles:
    - node
    - docker
    - master-lb
