- hosts: all
  remote_user: vagrant
  become: yes
  roles:
    - preinstall

- hosts: k8s-console
  remote_user: vagrant
  become: yes
  roles:
    - download
    - makessl
    - docker
    - master-lb
    - { role: kubernetes/client }

- hosts: k8s-master
  remote_user: vagrant
  become: yes
  roles:
    - etcd
    - { role: kubernetes/master }


- hosts: k8s-node
  remote_user: vagrant
  become: yes
  roles:
    - docker
    - master-lb
    - { role: kubernetes/node }
