---
- name: Create cert directory
  file:
    path: "{{ certs_dir }}"
    state: directory
    mode: 0755
    owner: root
    recurse: yes

- name: Generate CA config json file
  template:
    src: config.json.j2
    dest: "{{ certs_dir }}/config.json"
    owner: root
    mode: 0600

- name: Generate CA cert json file
  template:
    src: csr.json.j2
    dest: "{{ certs_dir }}/csr.json"
    owner: root
    mode: 0600

- name: Generate etcd cert json file
  template:
    src: etcd-csr.json.j2
    dest: "{{ certs_dir }}/etcd-csr.json"
    owner: root
    mode: 0600

- name: Generate kubernetes apiserver cert json file
  template:
    src: kube-apiserver-csr.json.j2
    dest: "{{ certs_dir }}/kube-apiserver-csr.json"
    owner: root
    mode: 0600

- name: Generate kubernetes controller manager cert json file
  template:
    src: kube-controller-manager-csr.json.j2
    dest: "{{ certs_dir }}/kube-controller-manager-csr.json"
    owner: root
    mode: 0600

- name: Generate kubernetes scheduler cert json file
  template:
    src: kube-scheduler-csr.json.j2
    dest: "{{ certs_dir }}/kube-scheduler-csr.json"
    owner: root
    mode: 0600

- name: Generate kubernetes proxy cert json file
  template:
    src: kube-proxy-csr.json.j2
    dest: "{{ certs_dir }}/kube-proxy-csr.json"
    owner: root
    mode: 0600
  when: kube_proxy_enabled

- name: Generate kubernetes console cert json file
  template:
    src: kube-admin-csr.json.j2
    dest: "{{ certs_dir }}/kube-admin-csr.json"
    owner: root
    mode: 0600
