- name: delete kube-router network_plugin
  shell: "kubectl delete -f {{ yaml_dir }}/kube-router.yaml"
  delegate_to: "{{ groups['k8s-console'][0] }}"
  ignore_errors: true
  run_once: yes

- name: uninstall kube-router if exists
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/cni/net.d

- name: create yaml file require directory
  file:
    path: "{{ yaml_dir }}"
    state: directory
  delegate_to: "{{ groups['k8s-console'][0] }}"

- name: gather certs for calico etcd endpoints
  slurp:
    src: "{{ item }}"
  register: calico_etcd_certs
  with_items:
    - "{{ certs_dir }}/ca.pem"
    - "{{ certs_dir }}/etcd.pem"
    - "{{ certs_dir }}/etcd-key.pem"
  delegate_to: "{{ groups['k8s-console'][0] }}"

- name: Generate Deployment YAML
  template:
    src: "calico.yaml.j2"
    dest: "{{ yaml_dir }}/calico.yaml"
  delegate_to: "{{ groups['k8s-console'][0] }}"

- name: create calico network_plugin
  shell: "kubectl apply -f {{ yaml_dir }}/calico.yaml"
  delegate_to: "{{ groups['k8s-console'][0] }}"
  run_once: yes
