---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dev
  name: devadmin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devadmin
  namespace: dev
subjects:
- kind: User
  name: devadmin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: devadmin
  apiGroup: rbac.authorization.k8s.io
