# install kubelet
- name: create kubelet-bootstrap user
  command: kubectl create clusterrolebinding kubelet-bootstrap --clusterrole=system:node-bootstrapper --user=kubelet-bootstrap
  ignore_errors: yes
  delegate_to: "{{ groups['k8s-console'][0] }}"
  run_once: yes

- name: gather certs for bootstrap kubeconfig
  slurp:
    src: "{{ item }}"
  register: bootstrap_certs
  with_items:
    - "{{ certs_dir }}/ca.pem"
  delegate_to: "{{ groups['k8s-console'][0] }}"

- name: write bootstrap kubeconfig
  template:
    src: bootstrap.kubeconfig.j2
    dest: "{{ certs_dir }}/bootstrap.kubeconfig"
    owner: root
    mode: 0640
  delegate_to: "{{ groups['k8s-console'][0] }}"

- name: create kube node require dir
  file:
    path: "{{ item }}"
    mode: 0700
    state: directory
    recurse: yes
    owner: "{{ kube_user }}"
    group: "{{ kube_user }}"
  with_items:
    - "{{ kube_certs_dir }}"

- name: sync bootstrap.kubeconfig to each node
  copy:
    src: "{{ certs_dir }}/bootstrap.kubeconfig"
    dest: "{{ kube_certs_dir }}"

- name: sync kubelet binary to each node
  copy:
    src: "{{ node_binary_dir }}/kubelet"
    dest: "{{ kube_bin_dir }}/kubelet"
    mode: 0755

- name: install kubelet systemd Unit
  with_items:
    - f: kubelet.service
      d: /usr/lib/systemd/system
  template:
    src: "{{ item.f }}.j2"
    dest: "{{ item.d }}/{{ item.f }}"
    mode: 0644
  notify:
    - reload systemd

- name: make sure kubelet service running
  systemd:
    name: kubelet
    state: started
    enabled: yes

- name: systemctl daemon-reload
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes



# install kube-proxy if kube-proxy is enabled and kube_network_plugin is calico

- name: gather certs for kube proxy
  slurp:
    src: "{{ item }}"
  register: kube_proxy_certs
  with_items:
    - "{{ certs_dir }}/ca.pem"
    - "{{ certs_dir }}/kube-proxy.pem"
    - "{{ certs_dir }}/kube-proxy-key.pem"
  delegate_to: "{{ groups['k8s-console'][0] }}"
  when: kube_proxy_enabled


- name: write kube proxy kubeconfig
  template:
    src: kube-proxy.kubeconfig.j2
    dest: "{{ certs_dir }}/kube-proxy.kubeconfig"
    owner: root
    mode: 0640
  delegate_to: "{{ groups['k8s-console'][0] }}"
  when: kube_proxy_enabled

- name: sync kube-proxy.kubeconfig to each node
  copy:
    src: "{{ certs_dir }}/kube-proxy.kubeconfig"
    dest: "{{ kube_certs_dir }}"
  when: kube_proxy_enabled

- name: sync kube proxy binary to each node
  copy:
    src: "{{ node_binary_dir }}/kube-proxy"
    dest: "{{ kube_bin_dir }}/kube-proxy"
    mode: 0755
  when: kube_proxy_enabled


- name: install kube proxy systemd Unit
  with_items:
    - f: kube-proxy.service
      d: /usr/lib/systemd/system
  template:
    src: "{{ item.f }}.j2"
    dest: "{{ item.d }}/{{ item.f }}"
    mode: 0644
  notify:
    - reload systemd
  when: kube_proxy_enabled

- name: make sure kube proxy service running
  systemd:
    name: kube-proxy
    state: started
    enabled: yes
  when: kube_proxy_enabled

- name: systemctl daemon-reload
  systemd:
    name: kube-proxy
    state: restarted
    daemon_reload: yes
  when: kube_proxy_enabled
