- name: Downloading
  debug:
    msg:
      - "URL: {{ download.url }}"
      - "Dest: {{ download.dest }}"

- name: Create dest directory
  file:
    path: "{{ local_release_dir }}/{{ download.dest|dirname }}"
    state: directory
    recurse: yes
  when:
    - download.enabled
    - download.file

- name: Download item
  get_url:
    url: "{{download.url}}"
    dest: "{{local_release_dir}}/{{download.dest}}"
    owner: "{{download.owner|default(omit)}}"
    mode: "{{download.mode|default(omit)}}"
  register: get_url_result
  util: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
  retries: 4
  delay: "{{ retry_stagger|random + 3}}"
  when:
    - download.enabled
    - download.file

- name: Extract archives
  unarchive:
    src: "{{ local_release_dir }}/{{download.dest}}"
    dest: "{{ local_release_dir }}/{{download.dest|dirname}}"
    owner: "{{ download.owner|default(omit) }}"
    mode: "{{ download.mode|default(omit) }}"
    copy: no
  when:
    - download.enabled
    - download.file
    - download.unarchive|default(False)
